server:
  port: 8080
  servlet:
    context-path: /clothing-store

spring:
  datasource:
    url: "jdbc:mysql://sql12.freesqldatabase.com:3306/sql12747309"
    username: sql12747309
    password: wCUl8SehHW
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true